disabled_rules:
  - trailing_whitespace
  - force_try
  - for_where
  - large_tuple
  - nesting
  
included: # paths to include during linting. `--path` is ignored if present.
  - Visyn

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Visyn/Resources

opt_in_rules:
  - attributes
  - closure_end_indentation
  - conditional_returns_on_newline
  - explicit_init
  - fatal_error_message
  - first_where
  - operator_usage_whitespace
  - vertical_parameter_alignment_on_call
  - let_var_whitespace
  - switch_case_on_newline
  - closure_spacing
  - trailing_closure
  - discouraged_direct_init
  - unneeded_parentheses_in_closure_argument
  - nesting
  - nimble_operator

force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
line_length: 180
file_length:
   warning: 400
   error: 600
  # ignore_comment_only_lines: true
type_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 50
  # excluded: iPhone # excluded via string
identifier_name:
  min_length: # only min_length
    warning: 2 # only warning

vertical_whitespace:
  max_empty_lines: 2

  excluded: # excluded via string array
  - id
  - URL
  - iv
  - cc
  - ad
  - up
  - preferredInterfaceOrientationForPresentation

closure_end_indentation: error
conditional_returns_on_newline: error
explicit_init: error
fatal_error_message: error
operator_usage_whitespace: warning
vertical_parameter_alignment_on_call: warning
switch_case_on_newline: warning

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)

custom_rules:

  mark_space:
    name: "Space Before MARK"
    regex: "((*\n)*\/\/ MARK)"
    message: "There should be a space before // MARK"
    severity: warning





